openapi: '3.0.0'
info:
  title: Adaptative Task
  version: 1.0.0
  contact:
    email: catalunha.mj@gmail.com
# servers:
#   - url: 

tags:
  - name: task

paths:
  /task:
    get:
      tags:
        - task
      summary: Encontrar todas as tarefas
      # description: Encontrar todas as tarefas
      operationId: taskGet
      responses:
        '200':
          description: Leitura bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '403':
          description: acesso negado
    post:
      tags:
        - task
      summary: Salva uma Tarefa
      operationId: taskPost
      requestBody:
        description: Criar uma nova tarega
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
            examples:
              ex1:
                summary: Exemplo 1
                value: {"id": "4b763587-fcc8-4049-8a4c-95810bd2a3b4", "title": "Tarefa 02",  "description": "Tarefa 02 ...",  "status": true}
              ex2:
                summary: Exemplo 2
                externalValue: '/home/catalunha/myapp/adaptative/docs/oas/task.json'
                # value: {"id": "4b763587-fcc8-4049-8a4c-95810bd2a3b4", "title": "Tarefa 03",  "description": "Tarefa 03 ...",  "status": true}
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '405':
          description: Operação invalida



components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          example: 4b763587-fcc8-4049-8a4c-95810bd2a3b4
        title:
          type: string
          example: Tarefa (comp 1)
        description:
          type: string
          example: Tarefa ...
        status:
          type: boolean
          example: true
    Task2:
      type: object
      properties:
        id:
          type: string
          example: 4b763587-fcc8-4049-8a4c-95810bd2a3b4
        title:
          type: string
          example: Tarefa (comp 2)
        description:
          type: string
          example: Tarefa ...
        status:
          type: boolean
          example: true        
  # requestBodies:
  #   Task:
  #     description: requestBodies ???
  #     content:
  #       application/json:
  #         schema:
  #           $ref: '#/components/schemas/Task'

